### ISSUE TITLE
Am getting an error when i run the payload on the target

### ISSUE THREAD

**Issue by ikewzer0** [hash3liZer/SillyRAT#11]
Please help me out with the error, i am getting the following error msg. Is it a requirement to have a X server running at the target ?

```
Traceback (most recent call last):
  File "cl.py", line 17, in <module>
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "pynput/__init__.py", line 40, in <module>
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "pynput/keyboard/__init__.py", line 31, in <module>
  File "pynput/_util/__init__.py", line 76, in backend
ImportError: this platform is not supported: No module named 'pynput.keyboard._xorg'

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
[18557] Failed to execute script cl
```

**Comment by hash3liZer** [comment]
No, which platform are you running it on?

**Comment by ikewzer0** [comment]
Linux (Ubuntu 20.04)

**Comment by hash3liZer** [comment]
Can you send me the command you used to compile the file? Also, are you executing on a server?

**Comment by ikewzer0** [comment]
the target is an Ubuntu 20.04 server. below is a screenshot of the command how i compile it

![2020-11-29_23-11](https://user-images.githubusercontent.com/21004441/100549870-86537900-3297-11eb-9aca-bfe155a42938.png)

**Comment by hash3liZer** [comment]
Ok, I identified the bug. Will solve it in the few coming days.

**Comment by devrix123** [comment]
hello, when I want to test the compiled files in my vm, it throws an error that there is a problem with this vm's architecture.
![gambar](https://user-images.githubusercontent.com/70104102/208306618-0564f697-b3cf-4bb3-bbf9-0a4933b4be05.png)

**Comment by wenyurush** [comment]
how about the bug

**Comment by hash3liZer** [comment]
@wenyurush actually i didn't get the time to solve it. If you can do a PR, that would be really helpful.
