### ISSUE TITLE
Windows Compilation Error & Issue With the payload

### ISSUE THREAD

**Issue by brouettelover** [hash3liZer/SillyRAT#23]
I face an issue while trying to generate a payload in Win10, the error was : 

```
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python310\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python310\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "C:\Users\Stickman\Vir\SillyRAT\super.exe.spec", line 6, in <module>
    a = Analysis(['C:\\Users\\Stickman\\Vir\\SillyRAT\\tmp\\cl.py'],
  File "C:\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 244, in __init__
    self.__postinit__()
  File "C:\Python310\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "C:\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 342, in assemble
    self.graph = initialize_modgraph(
  File "C:\Python310\lib\site-packages\PyInstaller\depend\analysis.py", line 729, in initialize_modgraph
    graph = PyiModuleGraph(
  File "C:\Python310\lib\site-packages\PyInstaller\depend\analysis.py", line 117, in __init__
    self._analyze_base_modules()
  File "C:\Python310\lib\site-packages\PyInstaller\depend\analysis.py", line 234, in _analyze_base_modules
    self._base_modules = [mod
  File "C:\Python310\lib\site-packages\PyInstaller\depend\analysis.py", line 236, in <listcomp>
    for mod in self.import_hook(req)]
  File "C:\Python310\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1480, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "C:\Python310\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1664, in _find_head_package
    raise ImportError("No module named " + target_package_name)
ImportError: No module named _bootlocale
```

I was able to solve this issue simply by downloading a new version of : pyinstaller

I've used this command to fix this Issue : 
`
 pip install pyinstaller==4.10
`
when the Exe is created, it seems that is missing this package : 

`pip install python3_xlib`

-----------------------------------

After this the payload is generated but it's not useable, I check with wireshark and it seems that the payload stay quite and don't try to communicate with my server that is running on my parrot OS.

I can help you with this project even if I'm kind of new of this type of programming.

**Comment by hash3liZer** [comment]
Hi, i got the issue. The thing is it might take me some time to make the change and test it. If its easy for you to do a pull request, that would be really helpful to me. Otherwise, i will put this issue on the list and will sort this out in meantime.
